version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/eytandecker/flightsim-mcp

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unparam
          - errcheck
