run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/eytandecker/flightsim-mcp

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unparam
